### ISSUE TITLE
Problems compiling

### ISSUE THREAD

**Issue by arnisjuraga** [luigitni/git-estimate#1]
If I just `git clone ...` this repo, then I had problems compiling un Ubuntu 18.04 WSL (Windows Linux Subsystem)

```
main.go:6:2: cannot find package "git-estimate/estimate" in any of:
        /usr/lib/go-1.10/src/git-estimate/estimate (from $GOROOT)
        /home/arnis/go/src/git-estimate/estimate (from $GOPATH)
main.go:7:2: cannot find package "gopkg.in/src-d/go-git.v4" in any of:
        /usr/lib/go-1.10/src/gopkg.in/src-d/go-git.v4 (from $GOROOT)
        /home/arnis/go/src/gopkg.in/src-d/go-git.v4 (from $GOPATH)
main.go:8:2: cannot find package "gopkg.in/src-d/go-git.v4/plumbing/object" in any of:
        /usr/lib/go-1.10/src/gopkg.in/src-d/go-git.v4/plumbing/object (from $GOROOT)
        /home/arnis/go/src/gopkg.in/src-d/go-git.v4/plumbing/object (from $GOPATH)
```

1. needed to "move" repo to `~/go/src/git-estimate/` location
2. Exec  `go get gopkg.in/src-d/go-git.v4`

For ease, I also added
`cp ~/go/src/git-estimate/git-estimate /usr/local/bin/git-estimate`

**Comment by luigitni** [comment]
Hi, sorry for the late response.
I would say it's an issue due to the go version you are using.
Git-estimates uses [Go Modules](https://github.com/golang/go/wiki/Modules) while it looks like your go installation is looking for dependencies inside the GOPATH.

I know it's kinda late but what version of Go were you running when you experienced the issue?
If version 1.11 make sure that Go Modules are enabled.

**Comment by joshpetit** [comment]
Putting the compiled binary in the releases might help people who don't have the sdk or have trouble compiling the program. Thanks for making this :).

**Comment by luigitni** [comment]
Thanks @joshpetit for the suggestion.
Binaries are now available in the ["Release" section of the repo](https://github.com/luigitni/git-estimate/releases/tag/v1.1.0).
